object Libs {
    private const val nav_version = "2.3.0"
    private const val kotlin_version = "1.3.72"
    private const val koin_version = "2.2.0-rc-2"
    private const val room_version = "2.2.5"
    private const val moshi_version = "1.11.0"
    private const val lifecycle_version = "2.2.0"

    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CONSTRAINT_LAYOUT_VERSION = "2.0.1"
    const val APP_COMPAT = "androidx.appcompat:appcompat"
    const val APP_COMPAT_VERSION = "1.2.0"
    const val LEGACY_SUPPORT = "androidx.legacy:legacy-support-v4"
    const val LEGACY_SUPPORT_VERSION = "1.0.0"
    const val LIFECYCLE_EXTENSIONS = "androidx.lifecycle:lifecycle-extensions"
    const val LIFECYCLE_EXTENSIONS_VERSION = lifecycle_version
    const val LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val LIFECYCLE_VIEWMODEL_VERSION = lifecycle_version
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib"
    const val KOTLIN_STDLIB_VERSION = kotlin_version
    const val CORE_KTX = "androidx.core:core-ktx"
    const val CORE_KTX_VERSION = "1.3.2"
    const val JUNIT = "junit:junit"
    const val JUNIT_VERSION = "4.13"
    const val JUNIT_EXT = "androidx.test.ext:junit"
    const val JUNIT_EXT_VERSION = "1.1.2"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val ESPRESSO_CORE_VERSION = "3.3.0"
    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview"
    const val RECYCLERVIEW_VERSION = "1.1.0"
    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment"
    const val NAVIGATION_FRAGMENT_VERSION = nav_version
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui"
    const val NAVIGATION_UI_VERSION = nav_version
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_FRAGMENT_KTX_VERSION = nav_version
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"
    const val NAVIGATION_UI_KTX_VERSION = nav_version
    const val NAVIGATION_DYNAMICS_FEATURES_FRAGMENT = "androidx.navigation:navigation-dynamic-features-fragment"
    const val NAVIGATION_DYNAMICS_FEATURES_FRAGMENT_VERSION = nav_version
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx"
    const val FRAGMENT_KTX_VERSION = "1.2.5"
    const val KOIN_CORE = "org.koin:koin-core"
    const val KOIN_CORE_VERSION = koin_version
    const val KOIN_ANDROIDX_SCOPE = "org.koin:koin-androidx-scope"
    const val KOIN_ANDROIDX_SCOPE_VERSION = koin_version
    const val KOIN_ANDROIDX_VIEWMODEL = "org.koin:koin-androidx-viewmodel"
    const val KOIN_ANDROIDX_VIEWMODEL_VERSION = koin_version
    const val KOIN_ANDROIDX_FRAGMENT = "org.koin:koin-androidx-fragment"
    const val KOIN_ANDROIDX_FRAGMENT_VERSION = koin_version
    const val KOIN_ANDROIDX_WORKMANAGER = "org.koin:koin-androidx-workmanager"
    const val KOIN_ANDROIDX_WORKMANAGER_VERSION = koin_version
    const val GOOGLE_MATERIAL = "com.google.android.material:material"
    const val GOOGLE_MATERIAL_VERSION = "1.2.1"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"
    const val ROOM_RUNTIME_VERSION = room_version
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_KTX_VERSION = room_version
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_COMPILER_VERSION = room_version
    const val LIFECYCLE_LIVEDATA = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_LIVEDATA_VERSION = "2.2.0"
    const val MOSHI_KOTLIN_CODEGEN = "com.squareup.moshi:moshi-kotlin-codegen"
    const val MOSHI_KOTLIN_CODEGEN_VERSION = "$moshi_version" //"1.10
    const val MOSHI_KOTLIN = "com.squareup.moshi:moshi-kotlin"
    const val MOSHI_KOTLIN_VERSION = moshi_version
    const val MOSHI = "com.squareup.moshi:moshi"
    const val MOSHI_VERSION = moshi_version
    const val TIMBER = "com.jakewharton.timber:timber"
    const val TIMBER_VERSION = "4.7.1"
}